Examples for tslint-documentation
aervin/tslint pull request #2
Opened 2018-01-15 18:49 UTC by Shinigami92

#### PR checklist

- [x] Addresses an existing issue: #3601
- [ ] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [x] Documentation update

#### Overview of change:

#### Is there anything you'd like reviewers to focus on?

I'm not an english native speaker, pls check my sentences :)

#### CHANGELOG.md entry:

[enhancement] Documentation examples for following rules: `arrow-return-shorthand`, `class-name`, `no-any`, `no-empty-interface`, `no-sparse-arrays`, `no-unnecessary-callback-wrapper`, `object-literal-sort-keys`, `one-variable-per-declaration`, `only-arrow-functions`, `prefer-template`, `radix`, `switch-default`, `typedef`, `use-isnan`

2018-01-15 22:14 UTC, aervin requested changes
Great work @Shinigami92! I just left some suggestions for the descriptions. Some of the suggestions are purely stylistic. Ignore those if you like.

2018-01-15 22:14 UTC, aervin commented on src/rules/arrowReturnShorthandRule.ts
> +                description: "Enforces to use shorthand for return.",
Maybe "Enforces usage of the shorthand return syntax when an arrow function's body does **not** span multiple lines."

2018-01-15 22:14 UTC, aervin commented on src/rules/arrowReturnShorthandRule.ts
> +                description: "Enforces to use shorthand for return also for multiline.",
"Enforces usage of the shorthand return syntax even when an arrow function's body spans multiple lines."

2018-01-15 22:14 UTC, aervin commented on src/rules/noEmptyInterfaceRule.ts
> +                description: "Disallows an empty interface.",
"Disallows empty interfaces."

2018-01-15 22:14 UTC, aervin commented on src/rules/noSparseArraysRule.ts
> +                description: "Disallow sparse arrays",
Disallows*

2018-01-15 22:14 UTC, aervin commented on src/rules/noUnnecessaryCallbackWrapperRule.ts
> +                description: "Disallow unnecessary callback wrappers",
Disallows*

2018-01-15 22:14 UTC, aervin commented on src/rules/objectLiteralSortKeysRule.ts
> +                description: "Forces to sort keys in an object by alphabetical order",
Requires that an object literal's keys be sorted alphabetically.

2018-01-15 22:14 UTC, aervin commented on src/rules/objectLiteralSortKeysRule.ts
> +                description: "Forces to sort keys in an object by alphabetical order",
I think this still needs updated.

2018-01-15 22:14 UTC, aervin commented on src/rules/onlyArrowFunctionsRule.ts
> +                description: "Disallow functions with the function keyword",
Disallows*

2018-01-15 22:14 UTC, aervin commented on src/rules/preferTemplateRule.ts
> +                description: "Forces to use template-strings",
"Enforces the use of template strings whenever possible."

2018-01-15 22:14 UTC, aervin commented on src/rules/preferTemplateRule.ts
> +                description: "Forces to use template-strings but allows up to one concatenation",
"Enforces the use of template strings, but allows up to one concatenation."

2018-01-15 22:14 UTC, aervin commented on src/rules/radixRule.ts
> +                description: "Requires the radix parameter to be specified when calling `parseInt`.",
"Requires the inclusion of the radix parameter when calling `parseInt`."

2018-01-15 22:14 UTC, aervin commented on src/rules/switchDefaultRule.ts
> +                description: "Require a `default` case in `switch` statements.",
Requires*

2018-01-15 22:14 UTC, aervin commented on src/rules/typedefRule.ts
> +                description: "Requires type definitions for call-signature",
call signatures*

2018-01-15 22:14 UTC, aervin commented on src/rules/typedefRule.ts
> +                description: "Requires type definitions for arrow-call-signature",
arrow call signatures*

2018-01-15 22:14 UTC, aervin commented on src/rules/typedefRule.ts
> +                description: "Requires type definitions for parameter",
parameters*

2018-01-15 22:14 UTC, aervin commented on src/rules/typedefRule.ts
> +                description: "Requires type definitions for arrow-parameter",
arrow function parameters*

2018-01-15 22:14 UTC, aervin commented on src/rules/typedefRule.ts
> +                description: "Requires type definitions for property-declaration",
property declarations*

2018-01-15 22:14 UTC, aervin commented on src/rules/typedefRule.ts
> +                description: "Requires type definitions for variable-declaration",
variable declarations

2018-01-15 22:14 UTC, aervin commented on src/rules/typedefRule.ts
> +                description: "Requires type definitions for member-variable-declaration",
member variable declarations*

2018-01-15 22:14 UTC, aervin commented on src/rules/typedefRule.ts
> +                description: "Requires type definitions for object-destructuring",
"Requires type definitions when destructuring objects."

2018-01-15 22:14 UTC, aervin commented on src/rules/typedefRule.ts
> +                description: "Requires type definitions for array-destructuring",
"Requires type definitions when destructuring arrays."

2018-01-15 22:14 UTC, aervin commented on src/rules/useIsnanRule.ts
> +                description: "Enforces use of the `isNaN()`.",
How about "Enforces usage of `isNan()`."

2018-01-17 16:46 UTC, Shinigami92 commented on src/rules/objectLiteralSortKeysRule.ts
> +                description: Lint.Utils.dedent`Requires that an object literal's keys be sorted by interface-definition.
Still not yet satisfying

2018-05-03 16:59 UTC, aervin commented
@Shinigami92 Looks awesome! You should open this on the primary TSLint repo so it can be reviewed there.

2018-05-03 17:05 UTC, Shinigami92 commented
@aervin Pull requested on https://github.com/palantir/tslint/pull/3869

2025-06-09 10:49 UTC, closed without merging